name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
        targets: "i686-pc-windows-gnu"
    - name: Build
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: "target/i686-pc-windows-gnu/release/dinput8.dll"
            
    
